### PR TITLE
getTable() function to return table string instead of printing it

### PR DESCRIPTION
**Pull request by GCrispino**
I just created a function to return the created table string instead of printing it, because I wanted to save tables to a file and I couldn't. Now the module exports a function called `getTable()` to do that.

To make this I had to create other new function called `getTitleTable`, that does the same thing as `printTitleTable`, but does not print anything and instead it saves the table information into one string and at the end returns it. Also, I added one more argument to the function `printTableWithColumnTitles`. If it's true, the computed information is not printed, but saved to a string like on the other function. So, its new signature is `printTableWithColumnTitles(titles, items, noConsole)`.

### CODE REVIEW

**Comment by bahmutov** [comment]
Hey, nice work - question - should the readme be updated? Is this breaking existing users?

**Comment by GCrispino** [comment]
> Hey, nice work - question - should the readme be updated?
I think so. I'm kind of knew to this, should I update the readme and create another pull request? Or we can work this out only with this current PR?

> Is this breaking existing users?
I don't think so because I tested because a couple of functions were created to do this new feature. Based on my tests using Node the console.table() function still works as expected.

**Comment by bahmutov** [comment]
Sure, keep adding commits to the same branch and they should be added to this pull request automatically. I just want to see in the READMe how to use your new exported function.

**Comment by GCrispino** [comment]
Ok, cool! I'll let you know as soon as I do this

**Comment by GCrispino** [comment]
Hey, I just updated the readme :)

**Comment by bahmutov** [comment]
I have merged your pull request, but I am thinking I will probably make the table formatting method into a separate repo, while this repo will just use it. It seems to make sense - if you need easy table format, then use it. If you need to register `console.table`, then you use `console.table`

**Comment by GCrispino** [comment]
Cool! Do as you'd like. Thanks for merging it :)

**Pull request merged**
